// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZPQMQ68tHrd-6O0GUMc2HoKYYEl6XBQ',
    appId: '1:783190571591:web:47c6386bd634d77aa84f62',
    messagingSenderId: '783190571591',
    projectId: 'ebook-4a386',
    authDomain: 'ebook-4a386.firebaseapp.com',
    storageBucket: 'ebook-4a386.firebasestorage.app',
    measurementId: 'G-ND0KQ4J9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Z4sXP6yoCH65FD_GiVPzo_dRfFsusyk',
    appId: '1:783190571591:android:bdcaca9750deebbca84f62',
    messagingSenderId: '783190571591',
    projectId: 'ebook-4a386',
    storageBucket: 'ebook-4a386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvdO2B46Wz0nLOP_suH60pwWc5wVI1gY',
    appId: '1:783190571591:ios:5c9a7368cd07ac44a84f62',
    messagingSenderId: '783190571591',
    projectId: 'ebook-4a386',
    storageBucket: 'ebook-4a386.firebasestorage.app',
    iosBundleId: 'com.example.ebook',
  );
}
